# linear 1 using (name.csv)

In [1]:
# import required packages
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np

In [2]:
# load data
data = pd.read_csv(r"C:\Users\user\Desktop\ML Algorithm\Name.csv") # create file with Weight & Height
data


Weight  Height
0       56    1.60
1       66    1.45
2       77    1.44
3       56    1.50
4       34    1.07
5       56    1.63
6       23    1.22
7       45    1.35
8       23    1.33
9       89    1.07
10     104    1.45
11      34    1.02
12      58    1.00
13      65    1.60
14      76    1.59
15      59    1.58
16      95    1.57
17      98    1.55
18      89    1.45
19      34    1.44

In [3]:
data.shape

(20, 2)

In [4]:
# prepare our data so that model can be fitted
X = data.Weight.values
X


array([ 56,  66,  77,  56,  34,  56,  23,  45,  23,  89, 104,  34,  58,
        65,  76,  59,  95,  98,  89,  34], dtype=int64)

In [5]:
X = X.reshape(-1,1)
X



array([[ 56],
       [ 66],
       [ 77],
       [ 56],
       [ 34],
       [ 56],
       [ 23],
       [ 45],
       [ 23],
       [ 89],
       [104],
       [ 34],
       [ 58],
       [ 65],
       [ 76],
       [ 59],
       [ 95],
       [ 98],
       [ 89],
       [ 34]], dtype=int64)

In [6]:
y = data.Height.values
y

array([1.6 , 1.45, 1.44, 1.5 , 1.07, 1.63, 1.22, 1.35, 1.33, 1.07, 1.45,
       1.02, 1.  , 1.6 , 1.59, 1.58, 1.57, 1.55, 1.45, 1.44])

In [7]:
# initializing model

linreg = LinearRegression()

# fiiting training data

model = linreg.fit(X,y)

# target prediction

ypre = model.predict(X) # xtrain,xtest,ytrain,ytest



In [8]:
y # actual output

array([1.6 , 1.45, 1.44, 1.5 , 1.07, 1.63, 1.22, 1.35, 1.33, 1.07, 1.45,
       1.02, 1.  , 1.6 , 1.59, 1.58, 1.57, 1.55, 1.45, 1.44])

In [9]:
ypre # predicted output

array([1.37734331, 1.40838038, 1.44252116, 1.37734331, 1.30906176,
       1.37734331, 1.27492099, 1.34320254, 1.27492099, 1.47976564,
       1.52632124, 1.30906176, 1.38355073, 1.40527668, 1.43941745,
       1.38665444, 1.49838788, 1.507699  , 1.47976564, 1.30906176])

In [10]:
# model evaluation
mse = mean_squared_error(y,ypre) # ((y-yhat)**2/n-2)
rmse = np.sqrt(mse) # SQRT(mse)

score_value = linreg.score(X,y)

print('training time errors:',score_value)
print('testing time errors:',rmse)



training time errors: 0.13690621735623876
testing time errors: 0.18983747027614067


In [11]:
print('models - training - accuracy score is:',int((100-(score_value*100))),'%')

print('models - testing - accuracy score is:',int((100-(rmse*100))),'%')

models - training - accuracy score is: 86 %
models - testing - accuracy score is: 81 %
