# Random Forest Classifier

In [16]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [17]:
path="C:/Users/user/Desktop/ML Algorithm/iris.csv"

In [18]:
header_names=['sepal_length','sepal_width','petal_length','petal_width','class']


In [19]:
dataset=pd.read_csv(path,names=header_names)

In [20]:
dataset.head() # prints only top 5 records

sepal_length  sepal_width  petal_length  petal_width   class
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [21]:
X=dataset.iloc[:,0:4].values
print(X.shape)
print(X[:5])

(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [22]:
y=dataset.iloc[:,4].values
y.shape
print(y[:5])

['Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa']


In [23]:
from sklearn.model_selection import train_test_split # to avoid overfitting


In [24]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [25]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
clfr=RandomForestClassifier(n_estimators=10,criterion='entropy')
clfr.fit(X_train,y_train)


RandomForestClassifier(criterion='entropy', n_estimators=10)

In [28]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix


In [29]:
ypre=clfr.predict(X_test)

output=confusion_matrix(y_test,ypre)

print('Confusion matrix output:\n ')
output

Confusion matrix output:
 


array([[15,  0,  0],
       [ 0, 14,  0],
       [ 0,  1,  8]], dtype=int64)

In [30]:
X_test.shape

(38, 4)

In [31]:
output1=classification_report(y_test,ypre)
print('Classification report')
print(output1)


Classification report
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        15
  Versicolor       0.93      1.00      0.97        14
   Virginica       1.00      0.89      0.94         9

    accuracy                           0.97        38
   macro avg       0.98      0.96      0.97        38
weighted avg       0.98      0.97      0.97        38



In [32]:
output2=accuracy_score(y_test,ypre)*100
print(output2)

97.36842105263158
